# Copyright (C) 2017 Project-ODE
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# Hyperswitch configuration for ODE-FeatureService api:annotation endpoints
# Author: Alexandre Degurse


swagger: '2.0'
info:
  version: '1.0.0-beta'
  title: ODE FeatureService Annotation API
  description: ODE FeatureService Annotation API
  termsofservice: TBD
  contact:
    name: ODE-Project Team
    email: TBD
    url: TBD
  license:
    name: GNU General Public Licence, v3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
paths:
  /:
    get:
      tags:
        - ODE FeatureService Annotation
      summary: List ODE FeatureService API entry points
      description: |
        This is the root of the ODE FeatureService Annotation
      produces:
        - application/json
      responses:
        '200':
          description: The queriable sub-items
          schema:
            $ref: '#/definitions/listing'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-monitor: false

  /tags:
    get:
      tags:
        - ODE FeatureService Annotation
      summary: Lists tags stored in FeatureService
      description: |
        Get the list of all tags stored in FeatureService
      produces:
        - application/json
      responses:
        '200':
          description: The list of all the tags stored in FeatureService
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - get_from_backend:
            request:
              uri: /{domain}/sys/test/annotation/tags
      x-monitor: false

  /tags/{tagId}:
    get:
      tags:
        - ODE FeatureService Annotation
      summary: Get a tags from FeatureService
      description: |
        Get the tags that correspond to the given id.
      produces:
        - application/json
      parameters:
        - name: tagId
          in: path
          description: The identifier of the wanted tags
          type: string
          required: true
      responses:
        '200':
          description: The tags that correspond to the given id.
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - get_from_backend:
            request:
              uri: /{domain}/sys/test/annotation/tags/{tagId}
      x-monitor: false


  /labels:
    get:
      tags:
        - ODE FeatureService Annotation
      summary: Lists labels stored in FeatureService
      description: |
        Get the list of all labels stored in FeatureService
      produces:
        - application/json
      responses:
        '200':
          description: The list of all the labels stored in FeatureService
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - get_from_backend:
            request:
              uri: /{domain}/sys/test/annotation/labels
      x-monitor: false

  /labels/{labelId}:
    get:
      tags:
        - ODE FeatureService Annotation
      summary: Get a label from FeatureService
      description: |
        Get the label that correspond to the given id.
      produces:
        - application/json
      parameters:
        - name: labelId
          in: path
          description: The identifier of the wanted label
          type: string
          required: true
      responses:
        '200':
          description: The label that correspond to the given id.
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - get_from_backend:
            request:
              uri: /{domain}/sys/test/annotation/labels/{labelId}
      x-monitor: false

    # post:
      # tags:
      #   - ODE FeatureService Annotation
      # summary: Submit labels
      # description: |
      #   User sends annotations
      # produces:
      #   - application/json
      # parameters:
      #   - name: tags-set-id
      #     in: path
      #     description: Identifies the file where the labels are stored
      #     type: string
      #     required: true
      #   - name: annotation
      #     in: formData
      #     description: User's annotation
      #     type: array
      #     required: true
      # responses:
      #   '200':
      #     description: session token
      #     schema:
      #       $ref: '#/definitions/token'
      #   '401':
      #     description:  authentication problem
      #     schema:
      #       $ref: '#/definitions/problem'
      #   default:
      #     description: Error
      #     schema:
      #       $ref: '#/definitions/problem'
      # x-request-handler:
      #   - post_to_backend:
      #       request:
      #         method: post
      #         uri: /{domain}/sys/annotation/new/{file-set-id}
      #         headers:
      #           content-type: multipart/form-data
      #         body:
      #           annotation: '{{annotation}}'
      # x-monitor: false

definitions:
  # A https://tools.ietf.org/html/draft-nottingham-http-problem
  problem:
    required:
      - type
    properties:
      type:
        type: string
      title:
        type: string
      detail:
        type: string
      instance:
        type: string

  listing:
    description: The result format for listings
    required:
      - items
    properties:
      items:
        type: array
        items:
          type: string

  labels:
    properties:
      items:
        type: array
        items:
          properties:
            ts:
              type : string
            val:
              type: number
              format: double

  annotations:
    properties:
      items:
        type: array
        items:
          properties:
            startts:
              type : string
            endts:
              type : string
            mean:
              type: number
              format: double
